package model.report;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

// K2558859_Report class represents various types of reports generated by the library system
public class K2558859_Report {
    private String reportId;
    private String reportType;
    private LocalDate generatedDate;
    private String content;

    // Constructor for K2558859_Report
    public K2558859_Report(String reportId, String reportType) {
        this.reportId = reportId;
        this.reportType = reportType;
        this.generatedDate = LocalDate.now();
        this.content = "";
    }

    // Getters
    public String getReportId() {
        return reportId;
    }

    public String getReportType() {
        return reportType;
    }

    public LocalDate getGeneratedDate() {
        return generatedDate;
    }

    public String getContent() {
        return content;
    }

    // Sets the content of the report
    public void setContent(String content) {
        this.content = content;
    }

    // Generates the report based on the report type
    public void generate() {
        System.out.println("Generating " + reportType + " report...");
        
        if (content.isEmpty()) {
            content = "Report data not available. Please populate report content.";
        }
        
        System.out.println("Report generated successfully on " + generatedDate);
    }

    // Displays the report content in a formatted manner
    public void display() {
        // Use LocalDateTime to include both date and time
        LocalDateTime now = LocalDateTime.now();

        // Define a formatter for both date and time
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

        // Format and display the date and time
        System.out.println("Report generated on: " + now.format(formatter));
        System.out.println();
        System.out.println(getContent());
    }

    // Adds a line to the report content
    public void addLine(String line) {
        if (!content.isEmpty()) {
            content += "\n";
        }
        content += line;
    }

    @Override
    public String toString() {
        return "K2558859_Report{" +
                "reportId='" + reportId + '\'' +
                ", reportType='" + reportType + '\'' +
                ", generatedDate=" + generatedDate +
                '}';
    }
}
