package model.report;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 * Report class represents various types of reports generated by the library system.
 * Supports reports like most borrowed books, active borrowers, and overdue books.
 */
public class Report {
    private String reportId;
    private String reportType;
    private LocalDate generatedDate;
    private String content;

    /**
     * Constructor for Report.
     * @param reportId Unique identifier for the report
     * @param reportType Type of report (e.g., "Most Borrowed Books", "Active Borrowers", "Overdue Books")
     */
    public Report(String reportId, String reportType) {
        this.reportId = reportId;
        this.reportType = reportType;
        this.generatedDate = LocalDate.now();
        this.content = "";
    }

    // Getters
    public String getReportId() {
        return reportId;
    }

    public String getReportType() {
        return reportType;
    }

    public LocalDate getGeneratedDate() {
        return generatedDate;
    }

    public String getContent() {
        return content;
    }

    /**
     * Sets the content of the report.
     * @param content The report content/data
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * Generates the report based on the report type.
     * This method should be called by the LibraryManagementSystem with appropriate data.
     */
    public void generate() {
        System.out.println("Generating " + reportType + " report...");
        
        if (content.isEmpty()) {
            content = "Report data not available. Please populate report content.";
        }
        
        System.out.println("Report generated successfully on " + generatedDate);
    }

    /**
     * Displays the report content in a formatted manner.
     */
    public void display() {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        
        System.out.println("\n" + "=".repeat(80));
        System.out.println("LIBRARY MANAGEMENT SYSTEM - REPORT");
        System.out.println("=".repeat(80));
        System.out.println("Report ID: " + reportId);
        System.out.println("Report Type: " + reportType);
        System.out.println("Generated Date: " + generatedDate.format(formatter));
        System.out.println("-".repeat(80));
        System.out.println("\nREPORT CONTENT:");
        System.out.println(content);
        System.out.println("\n" + "=".repeat(80));
    }

    /**
     * Adds a line to the report content.
     * Useful for building reports incrementally.
     * @param line The line to add to the report
     */
    public void addLine(String line) {
        if (!content.isEmpty()) {
            content += "\n";
        }
        content += line;
    }

    @Override
    public String toString() {
        return "Report{" +
                "reportId='" + reportId + '\'' +
                ", reportType='" + reportType + '\'' +
                ", generatedDate=" + generatedDate +
                '}';
    }
}